import React, { useEffect, useMemo, useRef, useState } from 'react';
import Head from 'next/head';
import { AnimatePresence, motion } from 'framer-motion';
import { NavBar } from '../components/Shared';

type Line = { id: number; name: string; voltage_kv: number | null };
type Evidence = { label: string; value: string; source: string; timestamp: string; category: 'weather' | 'physical' };
type Citation = { source: string; source_url?: string };
type TimelineItem = { stage: string; detail: string; timestamp: string; status: string };
type RiskScore = { line_id: number; score: number; timestamp: string; evidence?: Evidence[]; contributions?: Record<string, number>; citations?: Citation[]; decision?: { recommendation: string; confidence: number; action_mode: string; reason: string }; decision_timeline?: TimelineItem[]; data_mode?: string };

const api = (process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000').replace(/\/$/, '');
const ease = [0.22, 1, 0.36, 1] as const;
const reveal = { initial: { opacity: 0, y: 26 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '-12%' }, transition: { duration: .75, ease } };
const DataModeContext = React.createContext<string | undefined>(undefined);

function Time({ value }: { value?: string }) { const d = value ? new Date(value) : null; return <>{d && !Number.isNaN(d.getTime()) ? d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : value || 'awaiting sync'}</>; }
function Eyebrow({ children }: { children: React.ReactNode }) { return <span className="maple-overline maple-console-overline">{children}</span>; }
function DataMode() { const mode = React.useContext(DataModeContext); const live = mode === 'live Mireye response'; return <span className="map-data-mode" aria-live="polite">{live ? '● LIVE MIREYE' : mode ? '● DEMO / FALLBACK DATA' : '● CONNECTING'}</span>; }

function FieldMap({ critical, loading, lineName, score, wind }: { critical: boolean; loading: boolean; lineName: string; score: number; wind: string }) {
  return <div className={'field-map ' + (critical ? 'critical' : '')}>
    <div className="field-map-terrain" />
    <svg viewBox="0 0 1000 620" preserveAspectRatio="none" aria-label="Maple field intelligence map">
      <defs><linearGradient id="maple-corridor" x1="0" x2="1" y1="0" y2="1"><stop stopColor="#9adff6" stopOpacity=".12"/><stop offset=".5" stopColor="#f8b36a" stopOpacity=".4"/><stop offset="1" stopColor="#ff7168" stopOpacity=".16"/></linearGradient></defs>
      <path className="terrain-line" d="M-20 118C170 58 211 210 370 116S647 51 752 151s182 91 278-4"/><path className="terrain-line" d="M-20 256c161-88 274 67 407-27s266-97 376 32 164 94 237-15"/><path className="terrain-line" d="M-20 428c166-97 266 43 401-60s279-98 390 21 159 102 249-2"/>
      <path className="field-river" d="M-30 507c162-76 257 53 398-16s254-58 389 7 177 104 275 27"/>
      <path className="field-corridor" d="M119 505c139-111 239-103 344-184S664 183 875 82l63 62c-193 102-296 226-433 277S286 471 192 565z"/>
      <path className="line-shadow" d="M121 501c144-111 239-104 348-180S663 185 878 87"/><path className="transmission-line" d="M121 484c144-111 239-104 348-180S663 168 878 70"/>
      <g className="towers"><g transform="translate(205 407)"><path d="M0 94 27 0l27 94M11 60h32M4 84h46M27 0v108"/></g><g transform="translate(470 278)"><path d="M0 94 27 0l27 94M11 60h32M4 84h46M27 0v108"/></g><g transform="translate(722 145)"><path d="M0 94 27 0l27 94M11 60h32M4 84h46M27 0v108"/></g></g>
      <g className="canopy"><circle cx="128" cy="308" r="33"/><circle cx="197" cy="278" r="43"/><circle cx="293" cy="235" r="29"/><circle cx="365" cy="196" r="42"/><circle cx="603" cy="101" r="48"/><circle cx="796" cy="240" r="44"/><circle cx="870" cy="299" r="30"/></g>
      <circle className="map-pulse" cx="500" cy="312" r="45"/><circle className="map-focus" cx="500" cy="312" r="10"/>
      <g className="map-hazards"><circle cx="421" cy="358" r="15"/><path d="m414 351 14 14m0-14-14 14"/><circle cx="589" cy="244" r="15"/><path d="m582 237 14 14m0-14-14 14"/></g>
    </svg>
    <i className="wind-flow wind-a">→</i><i className="wind-flow wind-b">→</i><i className="wind-flow wind-c">→</i>
    <div className="map-topline"><span><i /> <DataMode /></span><span>CALIFORNIA TRANSMISSION CORRIDOR</span></div>
    <div className="map-place"><b>{lineName}</b><small>active monitored span</small></div>
    <div className="map-score"><span>WILDFIRE RISK</span><b>{score.toFixed(1)}<em>%</em></b><small>{wind || 'Awaiting wind telemetry'}</small></div>
    <div className="map-key"><span><i className="key-corridor"/> exposure corridor</span><span><i className="key-line"/> transmission line</span><span><i className="key-canopy"/> vegetation</span></div>
    <AnimatePresence>{loading && <motion.div className="field-map-loader" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><i/><b>Maple is reading this landscape</b><span>Gathering live weather and physical-world intelligence…</span></motion.div>}</AnimatePresence>
  </div>;
}

export default function Console() {
  const [lines, setLines] = useState<Line[]>([]); const [selected, setSelected] = useState(1); const [risk, setRisk] = useState<RiskScore | null>(null); const [loading, setLoading] = useState(true); const [offline, setOffline] = useState(false); const [scenario, setScenario] = useState<'live' | 'severe'>('live'); const [actionState, setActionState] = useState<'monitoring' | 'simulating' | 'secured'>('monitoring'); const [events, setEvents] = useState<string[]>(['Maple is ready to read the selected line.']);
  const request = useRef(0); const addEvent = (message: string) => setEvents(current => [message, ...current].slice(0, 4));
  useEffect(() => { fetch(api + '/seed', { method: 'POST' }).catch(() => undefined); fetch(api + '/lines').then(r => r.json()).then(setLines).catch(() => setOffline(true)); }, []);
  useEffect(() => { let active = true; const load = async () => { const id = ++request.current; setLoading(true); try { const suffix = scenario === 'severe' ? '?scenario=severe' : ''; const response = await fetch(api + '/risk/' + selected + suffix); if (!response.ok) throw new Error(); const data = await response.json(); if (!active || id !== request.current) return; setRisk(data); setOffline(false); addEvent('Field intelligence refreshed for ' + data.line_id + ' · risk ' + data.score + '%.'); } catch { if (active && id === request.current) setOffline(true); } finally { if (active && id === request.current) setLoading(false); } }; if (!lines.length) return () => { active = false; }; load(); const interval = window.setInterval(load, 45000); return () => { active = false; window.clearInterval(interval); }; }, [lines.length, selected, scenario]);
  const activeLine = lines.find(line => line.id === selected); const evidence = risk?.evidence || []; const weather = evidence.filter(item => item.category === 'weather'); const physical = evidence.filter(item => item.category === 'physical'); const wind = weather.find(item => item.label === 'Wind speed')?.value || ''; const highRisk = Boolean(risk && risk.score >= 70 && actionState !== 'secured'); const displayedScore = actionState === 'secured' ? 0 : risk?.score || 0; const drivers = useMemo(() => Object.entries(risk?.contributions || {}).sort((a, b) => b[1] - a[1]), [risk]);
  const chooseLine = (id: number) => { setSelected(id); setActionState('monitoring'); document.getElementById('maple-field-map')?.scrollIntoView({ behavior: 'smooth', block: 'center' }); };
  const toggleScenario = () => { setActionState('monitoring'); setScenario(current => current === 'live' ? 'severe' : 'live'); };
  const simulate = async () => { if (!highRisk) return; setActionState('simulating'); addEvent('Protective relay simulation started. No real infrastructure is contacted.'); await new Promise(resolve => window.setTimeout(resolve, 800)); try { await fetch(api + '/actuate/' + selected + '?scenario=severe', { method: 'POST' }); } catch { addEvent('Audit API unavailable; this local simulation remains recorded.'); } await new Promise(resolve => window.setTimeout(resolve, 650)); setActionState('secured'); addEvent('Simulated isolation complete. Protective action recorded in the audit trail.'); };
  useEffect(() => {
    document.querySelectorAll<HTMLElement>('.signal-row small').forEach((element, index) => {
      const item = [...weather, ...physical][index];
      if (item) element.textContent = `${item.source} · Updated ${new Date(item.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
    });
  }, [weather, physical]);
  return <div className="maple-meet-page"><Head><title>Meet Maple | Wildfire Operations</title></Head><NavBar />{offline && <div className="maple-api-note">Live API unavailable. Start the backend to inspect current intelligence.</div>}
    <DataModeContext.Provider value={risk?.data_mode}><main>
      <section className="meet-hero"><div className="meet-hero-orb"/><motion.div {...reveal} className="meet-wrap meet-hero-content"><Eyebrow>MEET MAPLE · AUTONOMOUS WILDFIRE OPERATIONS</Eyebrow><h1>Know the fireline<br />before it changes.</h1><p>Maple turns live weather and physical-world intelligence into a clear, explainable action for every monitored power line.</p><div className="hero-actions"><a href="#maple-field-map" className="hero-primary">Explore a monitored span <span>↓</span></a><span><i/> Live weather + cited physical-world evidence</span></div></motion.div><div className="hero-bottom meet-wrap"><div><b>Why it matters</b><span>Small changes in wind, fuel, terrain and exposure can turn a routine line into a high-consequence event.</span></div><div><b>What Maple does differently</b><span>Every recommendation remains traceable to the facts, sources and thresholds behind it.</span></div></div></section>
      <section className="meet-wrap story-section story-intro"><motion.div {...reveal}><Eyebrow>HOW THE AGENT WORKS</Eyebrow><h2>One calm workflow.<br />Every critical signal.</h2><p>Maple guides an operator from a monitored line to a confident decision, without hiding the evidence along the way.</p></motion.div><div className="story-steps">{[['01','Choose a transmission span','Start with the line you need to understand.'],['02','Maple reads the landscape','Live weather meets terrain, fuel, vegetation and nearby exposure.'],['03','See the reasoning','The risk engine weighs every factor in the open.'],['04','Act with context','Maple recommends the safest next move and records the path.']].map(([number,title,copy], index) => <motion.div {...reveal} transition={{ duration:.65, delay:index*.09, ease }} key={number} className="story-step"><b>{number}</b><div><h3>{title}</h3><p>{copy}</p></div></motion.div>)}</div></section>
      <section id="maple-field-map" className="meet-wrap map-section"><motion.div {...reveal} className="section-lead"><Eyebrow>01 · CHOOSE AND OBSERVE</Eyebrow><h2>Start with the line.<br />Maple reveals the context.</h2><p>Select a transmission span to see its active risk landscape. The map brings together weather movement, vegetation, terrain and the line corridor in one living view.</p></motion.div><div className="map-layout"><motion.aside {...reveal} className="line-picker"><span className="picker-label">MONITORED TRANSMISSION SPANS</span>{lines.map(line => <button key={line.id} onClick={() => chooseLine(line.id)} className={selected === line.id ? 'selected' : ''}><i className={selected === line.id && highRisk ? 'danger' : ''}/><span><b>{line.name.split(' (')[0]}</b><small>GRID-SPAN-{String(line.id).padStart(3,'0')} · {line.voltage_kv}kV</small></span><em>↗</em></button>)}<p><i/> Values update only when you choose a new span or change the scenario.</p></motion.aside><motion.div {...reveal} transition={{ duration:.8, delay:.08, ease }}><FieldMap critical={highRisk} loading={loading} lineName={activeLine?.name || 'Connecting to field intelligence'} score={displayedScore} wind={wind}/></motion.div></div></section>
      <section className="meet-wrap briefing-section"><motion.div {...reveal} className="section-lead"><Eyebrow>02 · INTELLIGENCE BRIEFING</Eyebrow><h2>Not just a number.<br />A field report you can inspect.</h2><p>Maple groups each incoming signal by its source system, keeps its timestamp visible, and shows which observations matter to this line.</p></motion.div><div className="briefing-grid"><motion.div {...reveal} className="briefing-copy"><span>LIVE CONDITIONS</span><h3>{scenario === 'severe' ? 'Severe conditions are being simulated.' : 'Weather is being read from the field.'}</h3><p>{scenario === 'severe' ? 'This labelled scenario demonstrates how Maple responds when wind, fuel dryness and exposure cross the protective threshold.' : 'Open-Meteo supplies the current wind, humidity and air temperature. Maple combines it with cited physical-world intelligence from Mireye.'}</p><button onClick={toggleScenario} disabled={loading} className={'scenario-cta ' + (scenario === 'severe' ? 'active' : '')}>{loading ? 'Refreshing intelligence…' : scenario === 'severe' ? 'Return to live conditions' : 'Run severe-weather demo'} <span>→</span></button></motion.div><motion.div {...reveal} transition={{ duration:.7, delay:.1, ease }} className="signal-list">{[...weather,...physical].map((item,index) => <div key={item.label} className="signal-row"><span>{String(index+1).padStart(2,'0')}</span><div><b>{item.label}</b><small>{item.source}</small></div><strong>{item.value}</strong></div>)}</motion.div></div>{risk?.citations && <motion.div {...reveal} className="source-row"><span>CITED DATASETS</span>{risk.citations.map(c => c.source_url ? <a key={c.source} href={c.source_url} target="_blank" rel="noreferrer">{c.source} ↗</a> : <i key={c.source}>{c.source}</i>)}</motion.div>}</section>
      <section className="reasoning-section"><div className="meet-wrap reasoning-layout"><motion.div {...reveal} className="reasoning-copy"><Eyebrow>03 · EXPLAINABLE REASONING</Eyebrow><h2>Maple shows<br />how it got there.</h2><p>The risk engine does not give a black-box result. It weighs the conditions around this span and turns the strongest signals into an explainable recommendation.</p><div className="confidence-note"><span>DECISION CONFIDENCE</span><b>{risk?.decision?.confidence || '--'}%</b><small>Based on weather freshness, cited physical intelligence, and evidence coverage.</small></div></motion.div><motion.div {...reveal} transition={{ duration:.75,delay:.1,ease }} className="driver-chart">{drivers.slice(0,5).map(([name,value],index) => <div key={name} className="driver-row"><div><span>{name}</span><b>{value.toFixed(1)}%</b></div><i><motion.em initial={{ width:0 }} whileInView={{ width:value+'%' }} viewport={{once:true}} transition={{duration:.8,delay:index*.08,ease}}/></i></div>)}</motion.div></div></section>
      <section className="meet-wrap decision-section"><motion.div {...reveal} className="decision-card"><div className="decision-glow"/><div className="decision-main"><Eyebrow>04 · MAPLE’S RECOMMENDATION</Eyebrow><span className="decision-risk">CURRENT WILDFIRE RISK</span><b className="decision-score">{displayedScore.toFixed(1)}<em>%</em></b><span className="decision-confidence">{risk?.decision?.confidence || '--'}% confidence</span></div><div className="decision-action"><span>{highRisk ? 'PROTECTIVE ACTION' : 'MONITORING STATE'}</span><h2>{actionState === 'secured' ? 'Segment secured in Maple’s sandbox.' : risk?.decision?.recommendation || 'Maple is collecting evidence.'}</h2><p>{risk?.decision?.reason || 'The recommendation will appear when the first field intelligence request completes.'}</p><div className="decision-next"><b>What happens next</b><span>{highRisk ? 'Record the simulated protective action in the audit trail.' : 'Continue monitoring as new evidence arrives every 45 seconds.'}</span></div><button onClick={simulate} disabled={!highRisk || actionState !== 'monitoring'}>{actionState === 'secured' ? 'Simulation complete · audit recorded' : actionState === 'simulating' ? 'Simulating protective response…' : highRisk ? 'Run protective simulation' : 'Monitoring remains active'} <i>→</i></button></div></motion.div></section>
      <section className="meet-wrap audit-section"><motion.div {...reveal} className="section-lead"><Eyebrow>05 · DECISION AUDIT</Eyebrow><h2>Every action keeps<br />its evidence trail.</h2><p>Maple records each stage from the incoming signal to the recommended protective response, so an operator always knows what happened and why.</p></motion.div><div className="audit-list">{(risk?.decision_timeline || []).map((item,index) => <motion.div {...reveal} transition={{duration:.55,delay:index*.08,ease}} key={item.stage}><span>{String(index+1).padStart(2,'0')}</span><i className={item.status === 'ready' ? 'ready' : ''}/><section><b>{item.stage}</b><p>{item.detail}</p></section><small><Time value={item.timestamp}/></small></motion.div>)}</div><div className="event-note">{events.map((event,index) => <span key={event+index}><i>0{events.length-index}</i>{event}</span>)}</div></section>
    </main></DataModeContext.Provider>
  </div>;
}
