import React, { useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { Footer, NavBar } from '../components/Shared';

const ease = [0.22, 1, 0.36, 1] as const;
const reveal = { initial: { opacity: 0, y: 32 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '-10%' }, transition: { duration: .8, ease } };
const flow = { initial: { opacity: 0, scale: .94 }, whileInView: { opacity: 1, scale: 1 }, viewport: { once: true, margin: '-10%' }, transition: { duration: .85, ease } };
function Label({ children }: { children: React.ReactNode }) { return <span className="platform-label">{children}</span>; }
function TerrainScene() { return <div className="platform-terrain"><div className="terrain-glow"/><div className="terrain-grid"/><svg viewBox="0 0 1000 520" preserveAspectRatio="none"><path className="terrain-contour" d="M-40 130C126 38 238 189 401 108s232-84 353 21 192 75 284-16"/><path className="terrain-contour" d="M-40 273c176-100 279 51 429-48s246-77 357 33 181 87 254-7"/><path className="terrain-contour" d="M-40 424c168-81 275 54 414-46s245-80 365 18 198 95 301-1"/><path className="terrain-river" d="M-20 454c153-76 237 41 386-19s254-55 392 3 182 96 275 17"/><path className="terrain-corridor" d="M105 478c145-103 248-102 373-178S682 172 885 61l61 61c-183 99-294 218-435 270S286 444 174 533z"/><path className="terrain-line" d="M111 461c145-104 248-103 373-178S686 155 891 45"/><g className="terrain-towers"><path d="M190 428l27-90 27 90m-43-37h32m-42 27h52m-26-80v105"/><path d="M461 290l27-90 27 90m-43-37h32m-42 27h52m-26-80v105"/><path d="M716 151l27-90 27 90m-43-37h32m-42 27h52m-26-80v105"/></g><g className="terrain-canopy"><circle cx="118" cy="296" r="38"/><circle cx="193" cy="243" r="46"/><circle cx="300" cy="215" r="32"/><circle cx="367" cy="166" r="45"/><circle cx="615" cy="92" r="52"/><circle cx="800" cy="221" r="45"/><circle cx="880" cy="288" r="34"/></g><circle className="terrain-pulse" cx="500" cy="293" r="48"/><circle className="terrain-focus" cx="500" cy="293" r="9"/></svg><div className="terrain-tag terrain-tag-top"><i/> LIVE SPAN CONTEXT <span>100 FT RESOLUTION</span></div><div className="terrain-tag terrain-tag-span"><b>Span 04</b><small>physical context resolved</small></div><div className="terrain-tag terrain-tag-risk"><span>RISK SURFACE</span><b>78<em>%</em></b><small>verified before action</small></div></div>; }
function SpanLens() { return <div className="span-lens" aria-label="A live physical-world view of one transmission span"><div className="lens-atmosphere"/><div className="lens-grid"/><div className="lens-orbit orbit-a"/><div className="lens-orbit orbit-b"/><div className="lens-orbit orbit-c"/><div className="lens-ridge ridge-a"/><div className="lens-ridge ridge-b"/><div className="lens-corridor"><i/><i/><i/><i/><i className="active"/><i/><i/><i/></div><div className="lens-center"><span>SPAN 04</span><b>context<br/>resolved</b><i/></div><div className="lens-signal lens-signal-a"><b>WIND</b><span>34 mph</span></div><div className="lens-signal lens-signal-b"><b>SOIL</b><span>9.2%</span></div><div className="lens-signal lens-signal-c"><b>CANOPY</b><span>dense</span></div><div className="lens-risk"><span>RISK</span><b>78<em>%</em></b><small>confidence checked</small></div><div className="lens-caption"><i/> PHYSICAL-WORLD EVIDENCE IN MOTION</div></div>; }
function BeforeAfter() { return <div className="before-after"><div className="legacy-field"><span className="comparison-kicker">BEFORE · AREA-WIDE RESPONSE</span><div className="legacy-region"><i/><i/><i/><i/><i/><b>COUNTY-WIDE<br/>DECISION</b></div><p>One broad risk condition can pull an entire service area into the same response.</p></div><div className="comparison-arrow"><span>→</span><small>physical evidence<br/>changes the unit of action</small></div><div className="maple-field"><span className="comparison-kicker">AFTER · MAPLE</span><div className="span-network"><i/><i/><i/><i/><i className="hot"/><i/><i/><i/><b>SPAN 04</b></div><p>Maple identifies the specific corridor under pressure, preserving context everywhere else.</p></div></div>; }
function MireyeScene() { const facts=[['SOIL','moisture'],['CANOPY','density'],['TERRAIN','slope'],['EXPOSURE','nearby structures']]; return <div className="mireye-scene"><div className="mireye-orbit orbit-one"/><div className="mireye-orbit orbit-two"/><div className="mireye-core"><span>PHYSICAL-WORLD</span><b>Mireye</b><small>evidence layer</small></div>{facts.map(([title,detail],i)=><div className={'mireye-fact mireye-fact-'+i} key={title}><i/><b>{title}</b><span>{detail}</span></div>)}<div className="mireye-weather"><i/> OPEN-METEO <span>wind · humidity · temperature</span></div></div>; }
function Pipeline() { const nodes=[['01','Observe','Mireye physical-world evidence'],['02','Contextualize','Live weather + span geometry'],['03','Reason','Weighted risk factors'],['04','Verify','Freshness + coverage + confidence'],['05','Recommend','A specific next action']]; return <div className="platform-pipeline">{nodes.map(([n,t,c],i)=><React.Fragment key={n}><motion.div {...flow} transition={{duration:.6,delay:i*.12,ease}} className={'pipeline-node node-'+i}><span>{n}</span><b>{t}</b><small>{c}</small><i/></motion.div>{i<nodes.length-1&&<div className="pipeline-link"><em/></div>}</React.Fragment>)}</div>; }
function DecisionScene() { const bars=[['Wind speed',72],['Soil dryness',84],['Canopy density',59],['Terrain slope',41],['Grid proximity',76]]; return <div className="decision-scene"><div className="decision-rings"/><div className="decision-score"><span>EXPLAINABLE RISK</span><b>78<em>%</em></b><small>Span 04</small></div><div className="decision-bars">{bars.map(([name,value],i)=><div key={name}><span>{name}</span><i><motion.em initial={{width:0}} whileInView={{width:value+'%'}} viewport={{once:true}} transition={{duration:.8,delay:i*.1,ease}}/></i><b>{value}</b></div>)}</div></div>; }
export default function Platform() { useEffect(()=>{window.history.scrollRestoration='manual';window.scrollTo(0,0);const id=requestAnimationFrame(()=>window.scrollTo(0,0));return()=>cancelAnimationFrame(id);},[]); return <div className="platform-v2 page-fade"><Head><title>Platform | Maple</title><meta name="description" content="How Maple turns physical-world evidence into explainable, span-level wildfire safety decisions."/></Head><NavBar/><main>
<section className="platform-hero platform-shell"><motion.div {...reveal} className="platform-hero-copy"><Label>THE MAPLE PLATFORM · PHYSICAL-WORLD INTELLIGENCE</Label><h1>When the line meets the landscape, <em>specificity matters.</em></h1><p>Wildfire risk is not evenly distributed across a county. It changes from one transmission span to the next—with the wind, terrain, fuel and exposure around it.</p><a href="#the-problem" className="platform-cta">Follow the decision path <span>↓</span></a></motion.div><motion.div {...flow} className="platform-hero-art"><SpanLens/></motion.div><div className="platform-hero-foot"><span><b>45s</b>scan interval</span><span><b>100 ft</b>span resolution</span><span><b>1 view</b>evidence to action</span></div></section>
<section id="the-problem" className="platform-shell platform-problem"><motion.div {...reveal}><Label>01 · THE PROBLEM</Label><h2>A wildfire decision can reach far beyond the line that caused it.</h2></motion.div><div className="problem-grid"><motion.p {...reveal}>Transmission infrastructure crosses terrain where a small shift in wind, dryness, canopy or nearby exposure can quickly become consequential—for communities, wildlife, utility crews and the wider grid.</motion.p><motion.div {...flow} className="impact-field"><span>COMMUNITIES</span><span>WILDLAND</span><span>GRID</span><span>INFRASTRUCTURE</span><i className="impact-line"/><i className="impact-spark"/></motion.div></div></section>
<section className="platform-shell platform-change"><motion.div {...reveal} className="change-copy"><Label>02 · WHY THIS NEEDS TO CHANGE</Label><h2>Broad mitigation loses the detail that makes a decision defensible.</h2><p>When one generalized signal represents an entire region, operators face an impossible trade-off: tolerate uncertainty or interrupt more service than the evidence supports. Maple gives each line its own physical context.</p></motion.div><motion.div {...flow}><BeforeAfter/></motion.div></section>
<section className="platform-mireye"><div className="platform-shell mireye-layout"><motion.div {...reveal}><Label>03 · THE MIREYE EVIDENCE LAYER</Label><h2>See the ground beneath the weather.</h2><p>Mireye provides the physical-world intelligence Maple needs to understand a transmission corridor: soil moisture, vegetation canopy, terrain slope and nearby building exposure. Maple joins that evidence with live Open-Meteo conditions, rather than treating a forecast as the whole landscape.</p><p className="mireye-note">The result is not a generic hazard map—it is cited physical context for the individual span being evaluated.</p></motion.div><motion.div {...flow}><MireyeScene/></motion.div></div></section>
<section className="platform-shell platform-mechanism"><motion.div {...reveal} className="mechanism-intro"><Label>04 · HOW MAPLE WORKS</Label><h2>Evidence becomes a recommendation through a visible chain of reasoning.</h2><p>Each stage contributes a clear, inspectable part of the decision. Nothing appears as a black-box instruction.</p></motion.div><Pipeline/></section>
<section className="platform-shell platform-reasoning"><motion.div {...flow}><DecisionScene/></motion.div><motion.div {...reveal} className="reasoning-copy"><Label>05 · THE DECISION ENGINE</Label><h2>A risk score that shows its work.</h2><p>Maple weighs live weather against the physical characteristics of the selected span. The strongest contributors remain visible, while evidence freshness, source coverage and model confidence are checked before the recommendation is surfaced.</p><div className="confidence-panel"><span>DECISION CONFIDENCE</span><b>96%</b><small>Live weather + cited physical-world evidence</small></div></motion.div></section>
<section className="platform-shell platform-action"><motion.div {...reveal} className="action-head"><Label>06 · AFTER THE DECISION</Label><h2>Protect the span. Keep the rest of the picture intact.</h2><p>When the selected span crosses Maple’s protective threshold, the operations view presents an explainable recommendation and its simulated SCADA protective action—together with the context for what happens next.</p></motion.div><motion.div {...flow} className="action-card"><div className="action-track"><i/><i/><i className="active"/><i/><i/><b>SPAN 04</b></div><div><span>RECOMMENDATION</span><h3>Isolate only the span under pressure.</h3><p>Simulated protective action, paired with a clear rationale and readiness for resilience routing.</p><Link href="/console" className="platform-cta">Open operations view <span>↗</span></Link></div></motion.div></section>
<section className="platform-shell platform-audit"><motion.div {...reveal}><Label>07 · THE AUDIT TRAIL</Label><h2>Every action retains the evidence behind it.</h2><p>Maple records the pathway from the incoming observation to the final recommendation, so teams can revisit what was known, what mattered and why the system responded.</p></motion.div><motion.div {...flow} className="audit-flow"><div><span>01</span><b>Weather ingested</b><small>Open-Meteo conditions attached</small></div><div><span>02</span><b>Physical evidence resolved</b><small>Mireye context cited</small></div><div><span>03</span><b>Risk reasoned</b><small>Contributors and confidence retained</small></div><div><span>04</span><b>Recommendation recorded</b><small>Simulated protective response ready</small></div></motion.div></section>
<section className="platform-shell platform-final"><motion.div {...reveal}><Label>MAPLE, IN CONTEXT</Label><h2>From a changing landscape to a deliberate decision.</h2><p>Explore the live operations experience to see evidence, risk reasoning and the decision trail for a monitored transmission span.</p><Link href="/console" className="platform-cta platform-cta-light">Meet Maple <span>↗</span></Link></motion.div></section>
</main><Footer/></div>; }
